### ISSUE TITLE
Question about long Delays for using Remote executor due to Queues awaiting

### ISSUE THREAD

**Issue by dd84ai** [AzBuilder/terraform-provider-terrakube#96]
![image](https://github.com/user-attachments/assets/72253480-6781-40c4-9855-3b83efbafee7)
Each time with i run `tofu plan` locally, for repo that has remote executor on i have long delays, from 1 to 5 queued runs phrase is visible
Is there a way somehow to make things faster running?

I expected faster plan builds

Our terrakube is running in this configuration
```yml
storage:
  defaultStorage: false
  aws:
    accessKey: ${aws_access_key}
    secretKey: ${aws_secret_key}
    bucketName: ${bucket_name}
    region: 'eu-west-1'

ui:
  version: 2.24.0
  nodeSelector:
      service: terrakube
  tolerations:
    - key: "service.example.net/terrakube"
      operator: "Exists"
      effect: "NoSchedule"

## API properties
api:
  version: 2.24.0
  defaultDatabase: false
  loadSampleData: false
  serviceAccountName: ${svc_name}
  podSecurityContext:
      runAsUser: 0
      runAsGroup: 1000
      fsGroup: 2000
  securityContext:
    runAsUser: 0
  env:
  - name: SERVICE_BINDING_ROOT
    value: /mnt/platform/bindings
  - name: JAVA_OPTS
    value: "-Xmx5G -Xms5G -XX:+UseG1GC -XX:MaxMetaspaceSize=5G"
  - name: ExecutorEphemeralNamespace
    value: terrakube
  - name: ExecutorEphemeralImage
    value: azbuilder/executor:2.24.0
  - name: ExecutorEphemeralSecret
    value: terrakube-executor-secrets
  properties:
    databaseType: "POSTGRESQL"
    databaseHostname: ${database_host}
    databaseName: ${database_name}
    databaseUser: ${database_user}
    databasePassword: ${database_password}
    databaseSslMode: "require"
    databasePort: "5432"
  resources:
    requests:
      cpu: "4"
      memory: 10Gi
  nodeSelector:
    service: terrakube
  tolerations:
    - key: "service.example.net/terrakube"
      operator: "Exists"
      effect: "NoSchedule"


executor:
  serviceAccountName: terrakube-svc
  properties:
    toolsRepository: "https://github.com/example/terrakube-extensions.git"
    toolsBranch: "master"
  env:
  - name: SERVICE_BINDING_ROOT
    value: /mnt/platform/bindings
  podSecurityContext:
    runAsUser: 0
    runAsGroup: 1000
    fsGroup: 2000
  securityContext:
    runAsUser: 0
  volumes:
    - name: aws-config-volume
      configMap:
        name: aws-config
  volumeMounts:
    - name: aws-config-volume
      mountPath: /root/.aws/config
      subPath: config
  resources:
    requests:
      memory: 1024Mi
      cpu: "500m"
  nodeSelector:
    service: terrakube
  tolerations:
    - key: "service.example.net/terrakube"
      operator: "Exists"
      effect: "NoSchedule"

## Registry properties
registry:
  enabled: true
  replicaCount: "1"
  env:
  - name: SERVICE_BINDING_ROOT
    value: /mnt/platform/bindings
  resources:
    requests:
      memory: "1024Mi"
      cpu: "500m"
  nodeSelector:
    service: terrakube
  tolerations:
    - key: "service.example.net/terrakube"
      operator: "Exists"
      effect: "NoSchedule"

security:
  dexClientId: ${openid_user}
  dexIssuerUri: https://terrakube-api.example.net/dex
  useOpenLDAP: false

dex:
  enabled: true
  podLabels:
    app: "terrakube-dex"
  config:
    issuer: https://terrakube-api.example.net/dex

    storage:
      type: memory
    web:
      http: 0.0.0.0:5556
      allowedOrigins: ['*']
      skipApprovalScreen: true
    oauth2:
      responseTypes: ["code", "token", "id_token"]

    connectors:
      - type: oidc
        id: keycloak
        name: keycloak
        config:
          issuer: https://accounts.example.com/realms/example
          clientID: ${openid_user}
          clientSecret: ${client_secret}
          redirectURI: https://terrakube-api.example.net/dex/callback
          scopes:
            - profile
            - email
            - groups
          insecureSkipEmailVerified: true
          insecureEnableGroups: true
          userIDKey: email
          userNameKey: email
          groupsKey: groups

    staticClients:
      - id: ${openid_user}
        redirectURIs:
          - 'https://terrakube.example.net'
          - 'https://terrakube.example.net/callback'
          - '/device/callback'
          - 'http://localhost:10000/login'
          - 'http://localhost:10001/login'
        name: ${openid_user}
        public: true
  resources:
    requests:
      memory: "500Mi"
      cpu: "250m"
  nodeSelector:
      service: terrakube
  tolerations:
    - key: "service.example.net/terrakube"
      operator: "Exists"
      effect: "NoSchedule"


## Ingress properties
ingress:
  useTls: true
  includeTlsHosts: true
  ui:
    enabled: true
    domain: "terrakube.example.net"
    path: "/*"
    pathType: "ImplementationSpecific"
    ingressClassName: "alb"
    tlsSecretName: tls-secret-ui-terrakube

  api:
    enabled: true
    domain: "terrakube-api.example.net"
    path: "/*"
    pathType: "ImplementationSpecific"
    ingressClassName: "alb"
    tlsSecretName: tls-secret-api-terrakube

  registry:
    enabled: true
    domain: "terrakube-reg.example.net"
    path: "/*"
    pathType: "ImplementationSpecific"
    ingressClassName: "alb"
    tlsSecretName: tls-secret-reg-terrakube

  dex:
    enabled: true
    path: "/dex"
    pathType: "ImplementationSpecific"
    ingressClassName: "alb"
```
